<script setup lang="ts">
import { computed, nextTick, reactive, ref, watch } from "vue";
import { ElMessage, type FormInstance, type FormRules, type UploadRequestOptions } from "element-plus";
import { Plus } from "@element-plus/icons-vue";
import { errorMessage } from "@/api/http";
import { resourceApi } from "@/api/services";
import type { Category, Dish, SetmealDish, SetmealPayload } from "@/types";

const props=defineProps<{modelValue:boolean;setmealId?:number}>();const emit=defineEmits<{"update:modelValue":[boolean];saved:[]}>();
const visible=computed({get:()=>props.modelValue,set:v=>emit("update:modelValue",v)});const formRef=ref<FormInstance>(),loading=ref(false),saving=ref(false),uploading=ref(false);
const categories=ref<Category[]>([]),dishCategories=ref<Category[]>([]),dishOptions=ref<Dish[]>([]);
const selectedDishCategoryId=ref<number>(),selectedDishId=ref<number>();
const form=reactive<SetmealPayload>({name:"",categoryId:0,price:0,status:1,description:"",image:"",setmealDishes:[]});
const rules:FormRules={name:[{required:true,message:"请输入套餐名称",trigger:"blur"}],categoryId:[{required:true,type:"number",min:1,message:"请选择套餐分类",trigger:"change"}],price:[{required:true,type:"number",min:.01,message:"价格必须大于 0",trigger:"blur"}],image:[{required:true,message:"请上传套餐图片",trigger:"change"}],setmealDishes:[{required:true,type:"array",min:1,message:"请至少选择一道菜品",trigger:"change"}]};
async function load(){Object.assign(form,{id:undefined,name:"",categoryId:0,price:0,status:1,description:"",image:"",setmealDishes:[]});selectedDishCategoryId.value=undefined;selectedDishId.value=undefined;dishOptions.value=[];loading.value=true;try{[categories.value,dishCategories.value]=await Promise.all([resourceApi.setmealCategories(),resourceApi.dishCategories()]);if(props.setmealId){const d=await resourceApi.setmealDetail(props.setmealId);Object.assign(form,{...d,price:d.price/100,setmealDishes:d.setmealDishes?.map(x=>({...x}))||[]})}}catch(e){ElMessage.error(errorMessage(e));visible.value=false}finally{loading.value=false;nextTick(()=>formRef.value?.clearValidate())}}
async function loadDishes(categoryId:number){selectedDishId.value=undefined;dishOptions.value=[];try{dishOptions.value=await resourceApi.dishesByCategory(categoryId)}catch(e){ElMessage.error(errorMessage(e))}}
function addDish(dishId:number){const dish=dishOptions.value.find(item=>item.id===dishId);if(!dish||form.setmealDishes.some(x=>x.dishId===dish.id))return;form.setmealDishes.push({dishId:dish.id,name:dish.name,price:dish.price,copies:1});selectedDishId.value=undefined}
function changeDishCategory(value?:number){if(value){loadDishes(value);return}dishOptions.value=[];selectedDishId.value=undefined}
function changeDish(value?:number){if(value)addDish(value)}
async function upload(options:UploadRequestOptions){uploading.value=true;try{form.image=await resourceApi.upload(options.file);options.onSuccess(form.image)}catch(e){ElMessage.error(errorMessage(e));throw e}finally{uploading.value=false}}
async function submit(){if(!await formRef.value?.validate().catch(()=>false))return;saving.value=true;try{const payload={...form,price:Math.round(form.price*100)};props.setmealId?await resourceApi.updateSetmeal(payload):await resourceApi.createSetmeal(payload);ElMessage.success("套餐已保存");visible.value=false;emit("saved")}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
watch(()=>props.modelValue,v=>{if(v)load()});
</script>
<template><el-dialog v-model="visible" :title="setmealId?'编辑套餐':'新增套餐'" width="min(760px,95vw)" destroy-on-close><div v-loading="loading"><el-form ref="formRef" :model="form" :rules="rules" label-position="top">
  <div class="dish-form-grid"><el-form-item label="套餐名称" prop="name"><el-input v-model.trim="form.name"/></el-form-item><el-form-item label="套餐分类" prop="categoryId"><el-select v-model="form.categoryId"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="套餐价格（元）" prop="price"><el-input-number v-model="form.price" :min=".01" :precision="2"/></el-form-item><el-form-item label="销售状态"><el-radio-group v-model="form.status"><el-radio :value="1">起售</el-radio><el-radio :value="0">停售</el-radio></el-radio-group></el-form-item></div>
  <el-form-item label="套餐图片" prop="image"><el-upload class="dish-uploader" :show-file-list="false" accept="image/png,image/jpeg,image/webp" :http-request="upload"><img v-if="form.image" :src="form.image"><div v-else class="upload-placeholder" v-loading="uploading"><el-icon><Plus/></el-icon><span>上传图片</span></div></el-upload></el-form-item>
  <el-form-item label="套餐描述"><el-input v-model="form.description" type="textarea" :rows="3" maxlength="200" show-word-limit/></el-form-item>
  <el-form-item label="选择菜品" prop="setmealDishes"><div class="dish-picker"><div class="dish-picker-controls"><el-select v-model="selectedDishCategoryId" placeholder="先选择菜品分类" clearable @change="changeDishCategory"><el-option v-for="c in dishCategories" :key="c.id" :label="c.name" :value="c.id"/></el-select><el-select v-model="selectedDishId" placeholder="选择菜品" clearable :disabled="!selectedDishCategoryId" @change="changeDish"><el-option v-for="d in dishOptions" :key="d.id" :label="d.name" :value="d.id"/></el-select></div><el-table :data="form.setmealDishes" empty-text="尚未选择菜品"><el-table-column prop="name" label="菜品"/><el-table-column label="份数" width="150"><template #default="{row}"><el-input-number v-model="row.copies" :min="1" size="small"/></template></el-table-column><el-table-column width="80"><template #default="{row}"><el-button link type="danger" @click="form.setmealDishes.splice(form.setmealDishes.indexOf(row),1)">移除</el-button></template></el-table-column></el-table></div></el-form-item>
</el-form></div><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="loading||uploading" @click="submit">保存套餐</el-button></template></el-dialog></template>
